### ISSUE TITLE
666，正好开始写这个页面。

### ISSUE THREAD

**Issue by AdminQQZ** [bingoogolapple/BGATransformersTip-Android#3]
先试试看,待会提几十个BUG给你。哈哈哈

**Comment by AdminQQZ** [comment]
![QQ截图20190902090442](https://user-images.githubusercontent.com/12959954/64084734-c2302380-cd60-11e9-93d5-a3e8595e967d.png)
这个角如何设置在左边
![QQ截图20190902090531](https://user-images.githubusercontent.com/12959954/64084746-d2480300-cd60-11e9-8b06-0c54ca447208.png)

**Comment by bingoogolapple** [comment]
* Java 代码中设置方式

```Java
.setArrowGravity(ArrowGravity.TO_TOP_ALIGN_START) // 设置箭头位于浮窗的左上角
.setArrowOffsetXDp(填写设计稿上的偏移量) // 设置箭头在 x 轴的偏移量
```

* 布局文件中设置方式
```xml
app:ad_arrowGravity="to_top_align_start"
app:ad_arrowExtraOffsetX="填写设计稿上的偏移量"
```
