### ISSUE TITLE
请楼主解释下为啥在RecyclerView的item点击时显示然后notify后就乱了，在listView中不会

### ISSUE THREAD

**Issue by bbbBBBSG** [bingoogolapple/BGATransformersTip-Android#4]
请楼主解释下为啥在RecyclerView的item点击时显示然后notify后就乱了，在listView中不会

**Comment by bingoogolapple** [comment]
item 在屏幕的位置变了吗？

**Comment by bingoogolapple** [comment]
![image](https://user-images.githubusercontent.com/8949716/64126991-88076600-cde2-11e9-8fea-97b6b84bd299.png)
![image](https://user-images.githubusercontent.com/8949716/64127003-948bbe80-cde2-11e9-9977-fa6174002fa9.png)

item 在屏幕的位置变了后浮窗会跟着动。如果 item 被移动到屏幕外回收，就会显示在最顶部，因为浮窗不会跟着移动到屏幕外部

这种情况把浮窗关了重新打开吧

![image](https://user-images.githubusercontent.com/8949716/64127186-37dcd380-cde3-11e9-9622-ce88427dcd10.png)
![image](https://user-images.githubusercontent.com/8949716/64127202-432fff00-cde3-11e9-8e2f-324d34f064b6.png)
