### ISSUE TITLE
屏幕边缘无法控制窗体位置。

### ISSUE THREAD

**Issue by zombiu** [bingoogolapple/BGATransformersTip-Android#6]
类似微信或者qq标题栏右上角弹框，在屏幕边缘，无法控制窗体位置。
锚点和箭头可以自己计算对齐，但是窗体想margin一下屏幕边缘，做不到啊！

**Comment by bingoogolapple** [comment]
* 通过下面两个属性来调整，但是不能移除到屏幕外部
```Java
setTipOffsetXDp(-10) // 设置浮窗在 x 轴的偏移量，等价于 marginRight 10
setTipOffsetYDp(5) // 设置浮窗在 y 轴的偏移量，等价于 marginTop 5
```
![image](https://user-images.githubusercontent.com/8949716/66838138-bc03a880-ef96-11e9-9a25-61cc510978b4.png)

**Comment by zombiu** [comment]
谢谢大佬！这个框架着实让人喜爱！
